### ISSUE TITLE
关于运行中的问题

### ISSUE THREAD

**Issue by Nanhh2000** [moen-hyb/Graph2MDA#1]
您好，您的代码是已经完善了吗，我在配置好环境后运行中仍然有很多bug（如定义函数不存在，参数值未设定等到）

**Comment by lihaicheng7003** [comment]
同样遇到很多问题，默认例子也跑不通
`Namespace(attributes=('features', 'similarity'), data_path='MDAD', dropout=0.5, epochs_net=200, epochs_net1=300, graphs=('net1', 'net2'), hidden1=800, hidden2=400, k_folds=10, lr=0.0005, model='gcn_vae', threshold=0.02, weight_decay=0)
Training MDAD
#############################
#############################
Training net1
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main()
  File "main.py", line 43, in main
    adj, features, labels, num_drug, num_microbe = load_data(dataset)
TypeError: load_data() missing 1 required positional argument: 'args'
`

**Comment by lihaicheng7003** [comment]
默认例子也跑不通

Namespace(attributes=('features', 'similarity'), data_path='MDAD', dropout=0.5, epochs_net=200, epochs_net1=300, graphs=('net1', 'net2'), hidden1=800, hidden2=400, k_folds=10, lr=0.0005, model='gcn_vae', threshold=0.02, weight_decay=0)
Training MDAD
#############################
#############################
Training net1
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main()
  File "main.py", line 43, in main
    adj, features, labels, num_drug, num_microbe = load_data(dataset)
TypeError: load_data() missing 1 required positional argument: 'args'

**Comment by youngbo9i** [comment]
我也跑了他的代码，确实有很多问题，我改了很大部分，也运行出来了，但是最后效果不是很好，可以的话你加我微信一起交流一下（18370634394）

**Comment by youngbo9i** [comment]
> 自然的例子也跑不通
> 
> Namespace(attributes=('features', 'similarity'), data_path='MDAD', dropout=0.5, epochs_net=200, epochs_net1=300, graphs=('net1', 'net2'), hidden1=800, hidden2= 400, k_folds=10, lr=0.0005, model='gcn_vae', threshold=0.02, weight_decay=0) 训练MDAD ###################### ##### ########################### 训练 net1 回溯（最近一次调用）： 文件“main.py” , line 89, in main() File "main.py", line 43, in main adj, features, labels, num_drug, num_microbe = load_data(dataset) TypeError: load_data() missing 1 required positional argument: 'args'

我也跑了他的代码，确实有很多问题，我改了很大部分，也运行出来了，但是效果不是很好（我可能是最后性能评价那里改的有问题），可以的话你加我微信一起交流一下（18370634394）

**Comment by jingjingyac** [comment]
Traceback (most recent call last):
  File "D:/code/Graph2MDA-master/Mine/main.py", line 88, in <module>
    main()
  File "D:/code/Graph2MDA-master/Mine/main.py", line 43, in main
    embeddings = train_gcn(features, adj, args, graph, num_drug, num_microbe)
  File "D:\code\Graph2MDA-master\Mine\trainGcn.py", line 29, in train_gcn
    adj_norm = preprocess_graph(adj)
  File "D:\code\Graph2MDA-master\Mine\preprocessing.py", line 16, in preprocess_graph
    adj_ = adj + sp.eye(adj.shape[0])
  File "D:\Anaconda\envs\pytorch\lib\site-packages\scipy\sparse\base.py", line 414, in __add__
    raise ValueError("inconsistent shapes")
ValueError: inconsistent shapes
跑不通 一直有问题

**Comment by moen-hyb** [comment]
这应该是你数据大小不对的问题&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "moen-hyb/Graph2MDA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 中午11:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [moen-hyb/Graph2MDA] 关于运行中的问题 (#1)





 
Traceback (most recent call last):
 File "D:/code/Graph2MDA-master/Mine/main.py", line 88, in 
 main()
 File "D:/code/Graph2MDA-master/Mine/main.py", line 43, in main
 embeddings = train_gcn(features, adj, args, graph, num_drug, num_microbe)
 File "D:\code\Graph2MDA-master\Mine\trainGcn.py", line 29, in train_gcn
 adj_norm = preprocess_graph(adj)
 File "D:\code\Graph2MDA-master\Mine\preprocessing.py", line 16, in preprocess_graph
 adj_ = adj + sp.eye(adj.shape[0])
 File "D:\Anaconda\envs\pytorch\lib\site-packages\scipy\sparse\base.py", line 414, in add
 raise ValueError("inconsistent shapes")
 ValueError: inconsistent shapes
 跑不通 一直有问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nanhh2000** [comment]
你好，请问data数据集中的net2是异构网络吗，如果是，为什么大小是1373×173呢？

**Comment by t9lex123** [comment]
请问p的shape因该改成什么那？

**Comment by t9lex123** [comment]
我看那个shape没错呀，是1373和173.

**Comment by t9lex123** [comment]
请问是要改成1228和123吗

**Comment by guoyanb** [comment]
loading labels...
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 43, in main
    embeddings = train_gcn(features, adj, args, graph, num_drug, num_microbe)
  File "/home/guoyb/Graph2MDA/trainGcn.py", line 18, in train_gcn
    adj_orig = adj_orig - sp.dia_matrix((adj_orig.diagonal()[np.newaxis, :], [0]).astype(np.float), shape=adj_orig.shape)
  File "/home/guoyb/anaconda3/envs/zzuli/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 538, in diagonal
    dtype=upcast(self.dtype))
  File "/home/guoyb/anaconda3/envs/zzuli/lib/python3.7/site-packages/scipy/sparse/sputils.py", line 51, in upcast
    raise TypeError('no supported conversion for types: %r' % (args,))
TypeError: no supported conversion for types: (dtype('O'),)
Hello, when I conduct experiments, I met the problem. Could you help me? Thanks a lot.
